// Code generated by "stringer -type=Strategy"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[inet4-0]
	_ = x[inet6-1]
	_ = x[resolv4-2]
	_ = x[resolv6-3]
}

const _Strategy_name = "inet4inet6resolv4resolv6"

var _Strategy_index = [...]uint8{0, 5, 10, 17, 24}

func (i Strategy) String() string {
	if i < 0 || i >= Strategy(len(_Strategy_index)-1) {
		return "Strategy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Strategy_name[_Strategy_index[i]:_Strategy_index[i+1]]
}
